# command line: main.py recognition -c config/st_gcn/ntu-xsub/test.yaml --weights work_dir/recognition/ntu-xsub/ST_GCN/epoch60_model.pt --batch_size 16 --device 0 --test_batch_size 16

base_lr: 0.01
batch_size: 16
config: config/st_gcn/ntu-xsub/test.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 60
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 16
test_feeder_args:
    data_path: ./data/NTU-RGB-D/xsub/val_data.npy
    label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: work_dir/recognition/ntu-xsub/ST_GCN/epoch60_model.pt
work_dir: ./work_dir/tmp
